### ISSUE TITLE
admin email and pass are statically bundled at build time

### ISSUE THREAD

**Issue by kennethklee** [arrowban/sveltekit-pocketbase-turborepo-template#1]
Great project.

Found an issue -- if you change your admin password, the web app needs to be rebuilt to create new accounts.

Looks like it's from this, since `$app/static/private` is injected at build time:
https://github.com/arrowban/sveltekit-pocketbase-turborepo-template/blob/167cfddb7b61a563ac80cbb2e5d03e3aa561478f/apps/web/src/routes/api/create-account/%2Bserver.js#L1

Suggestion:
```suggestion
import { env } from '$env/dynamic/private'; 
...
await pb.admins.authWithPassword(env.POCKETBASE_ADMIN_EMAIL, env.POCKETBASE_ADMIN_PASSWORD);
```

**Comment by arrowban** [comment]
@kennethklee Thanks!

Nice catch, I've updated the `/create-account` endpoint to use dynamic environment variables (https://github.com/arrowban/sveltekit-pocketbase-turborepo-template/commit/07dee0db30106f95503de45d904fe0191f0ea945)
